drop table if exists gameslides;

create table gameslides (
  id INTEGER primary key generated by default as identity,
  word TEXT NOT NULL,
  quote TEXT NOT NULL,
  imageurl TEXT NOT NULL,
);


insert into gameslides (word, quote, imageurl)
values
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
  
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
 
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png'),
 
  ('Introspection: The contemplation of your own thoughts and desires and conduct',
  'Stay hungry. Stay foolish. -Steve Jobs',
  'https://zenstatic.blob.core.windows.net/blog/p1cb8ot5dgi0i1jcl4011fnp14s9l.png');
