drop table if exists newusers;

CREATE TABLE users (
  id INTEGER primary key generated by default as identity,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL
);


insert into newusers (firstname, lastname, email, password)
values
  ('Terrance','Chang','tchang46343@gmail.com','Ferrari0');
  